name: "CSharp Build"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '19 0 * * 1'

permissions: read-all

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest
    permissions: 
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - run: |
        msbuild ./JulietTestSuite.sln /t:Rebuild /p:UseSharedCompilation=false
